name: integracao continua

on:
  pull_request:
    branches: ["prod", "dev"]

jobs:
  integracao-continua:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pdv
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: usando Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: run install, migrate, seed e test
        run: |
          npm install
          npm test
